export const START_PL_DOWNLOADING = 'START_DOWNLOADING'
export const FETCH_PL_ERROR = 'FETCH_PL_ERROR'
export const FETCH_PL_SUCCESS = 'FETCH_PL_SUCCESS'

export const ADD_P_TO_ORDER = 'ADD_P_TO_ORDER'
export const EDIT_ORDER_ITEM = 'EDIT_ORDER_ITEM'
export const REMOVE_P_FROM_ORDER = 'REMOVE_P_FROM_ORDER'
export const SEND_ORDER = 'SEND_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'