export const START_PL_DOWNLOADING = 'START_DOWNLOADING'
export const FETCH_PL_ERROR = 'FETCH_PL_ERROR'
export const FETCH_PL_SUCCESS = 'FETCH_PL_SUCCESS'

export const ADD_P_TO_SHOP_ORDER = 'ADD_P_TO_SHOP_ORDER'
export const EDIT_ORDER_SHOP_ITEM = 'EDIT_ORDER_SHOP_ITEM'
export const REMOVE_P_FROM_SHOP_ORDER = 'REMOVE_P_FROM_SHOP_ORDER'
export const ADD_P_TO_RESTAURANT_ORDER = 'ADD_P_TO_RESTAURANT_ORDER'
export const EDIT_ORDER_RESTAURANT_ITEM = 'EDIT_ORDER_RESTAURANT_ITEM'
export const REMOVE_P_FROM_RESTAURANT_ORDER = 'REMOVE_P_FROM_RESTAURANT_ORDER'

export const CHANGE_RESTAURANT_NAME = 'CHANGE_RESTAURANT_NAME'
export const CHANGE_SHOP_NAME = 'CHANGE_SHOP_NAME'
export const REMOVE_NAMES = 'REMOVE_NAMES'

export const SEND_ORDER = 'SEND_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'